#
# pyproject.toml
#

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
	"tests"
	]

[build-system]
requires = ["hatchling", "wheel"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["src"]
exclude = ["tests*"]

[tool.hatch.build.targets.wheel]
only-include = ["src"]

#[project.scripts]
#your-script = "your_package.module:main_function"

[project]
name = "noncom-bookkeeper"
version = "0.1.0"
description = "A bookkeeping application or non-commercial organizations."
readme = "README.rst"
authors = [
  {name = "Carl J. Nobile", email = "carl.nobile@gmail.com"},
]
maintainers = [
  {name = "Carl J. Nobile", email = "carl.nobile@gmail.com"},
]
license = {file = "LICENSE"}
dependencies = [
]
requires-python = ">= 3.10"
classifiers = [
  # How mature is this project? Common values are
  #   3 - Alpha
  #   4 - Beta
  #   5 - Production/Stable
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  #"Programming Language :: Python :: 3.14",
]

[project.urls]
url = "https://github.com/cnobile2012/noncom-bookkeeper"
Repository = "https://github.com/cnobile2012/noncom-bookkeeper"
