# -*- coding: utf-8 -*-
#
# data/default_bahai.toml
#
# This file provides data for the definition of fields used on
# the specified screens.
#
# TOML field definitions: https://toml.io/en/v1.0.0
#
# Noncommercial Bookkeeper META data
# ==================================
# display, report, both
#

[meta]
panels = ['config', 'budget']

[config]

[config.meta]
title = 'Organization Information'
bg_color = [50, 153, 204]
fg_color = [50, 50, 204]
tc_bg_color = [176, 192, 177]
font = [12, 'FONTFAMILY_DEFAULT', 'FONTSTYLE_NORMAL', 'FONTWEIGHT_BOLD', 0, '']

[config.sizers]
sizer_0 = ['BoxSizer', 'VERTICAL']
sizer_1 = ['FlexGridSizer', {grid=[4, 2, 0, 2], add=[0, 'EXPAND', 0]}]

[config.widgets]
widget_0 = ['StaticText', {args=['self', 'ID_ANY', 'Organization Name:'], min=[172, 23], focus=true, add=[0, 'ALIGN_CENTER_VERTICAL | LEFT | TOP', 6]}]
widget_1 = ['TextCtrl', {args=['self', 'ID_ANY', ''], min=[250, 32], add=[0, 'ALIGN_CENTER_VERTICAL | RIGHT | TOP', 6]}]

widget_2 = ['StaticText', {args=['self', 'ID_ANY', 'Total Membership:'], min=[172, 23], focus=false, add=[0, 'ALIGN_CENTER_VERTICAL | LEFT | TOP', 6]}]
widget_3 = ['TextCtrl', {args=['self', 'ID_ANY', ''], min=[50, 32], add=[0, 'ALIGN_CENTER_VERTICAL | RIGHT | TOP', 6]}]

widget_4 = ['StaticText', {args=['self', 'ID_ANY', 'Treasurer:'], min=[150, 23], focus=false, add=[0, 'ALIGN_CENTER_VERTICAL | LEFT | TOP', 6]}]
widget_5 = ['TextCtrl', {args=['self', 'ID_ANY', ''], min=[250, 32], add=[0, 'ALIGN_CENTER_VERTICAL | RIGHT | TOP', 6]}]

widget_6 = ['StaticText', {args=['self', 'ID_ANY', 'Start of Fiscal Year:'], min=[172, 23], focus=false, add=[0, 'ALIGN_CENTER_VERTICAL | LEFT | TOP', 6]}]
widget_7 = ['DatePickerCtrl', {args=['self', 'ID_ANY'], min=[115, 32], add=[0, 'ALIGN_CENTER_VERTICAL | RIGHT | TOP', 6]}]

[budget]

[budget.meta]
title = "Yearly Budget Worksheet"
#"The Spiritual Assembly of the Bahá'ís of <placeholder>"
bg_color = [129, 143, 74]
fg_color = [50, 50, 204]
tc_bg_color = [176, 192, 177]
font = [12, 'FONTFAMILY_DEFAULT', 'FONTSTYLE_NORMAL', 'FONTWEIGHT_BOLD', 0, '']
sizer_span = [[0, 0], 0, 0, 0]

[budget.sizers]
sizer_0 = ['BoxSizer', 'VERTICAL']
sizer_1 = ['FlexGridSizer', {grid=[14, 4, 2, 2], add=[1, 'EXPAND', 2]}]

[budget.widgets]
widget_0 = 'sizer_span'
widget_1 = ['StaticText', {args=['self', 'ID_ANY', 'Annual\nBudget'], style='ALIGN_CENTER_HORIZONTAL', add=[0, 'ALIGN_CENTER_VERTICAL | ALL', 2]}]
widget_2 = ['StaticText', {args=['self', 'ID_ANY', 'Year-to-Date\nActual'], style='ALIGN_CENTER_HORIZONTAL', add=[0, 'ALIGN_CENTER_VERTICAL | ALL', 2]}]
widget_3 = ['StaticText', {args=['self', 'ID_ANY', 'Monthly\nBudget'], style='ALIGN_CENTER_HORIZONTAL', add=[0, 'ALIGN_CENTER_VERTICAL | ALL', 2]}]
widget_4 = ['StaticText', {args=['self', 'ID_ANY', 'BEGGING CASH BALANCE AS OF:'], font=[10, 'FONTFAMILY_DEFAULT', 'FONTSTYLE_NORMAL', 'FONTWEIGHT_BOLD', 0, ""], add=[0, 'ALIGN_CENTER_VERTICAL | ALL', 2]}]
widget_5 = ['StaticText', {args=['self', 'ID_ANY', ''], style='ALIGN_CENTER_HORIZONTAL', add=[0, 'ALIGN_CENTER_VERTICAL | ALL', 2]}]


