#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Sun Jul 16 20:16:59 2023
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from config_page import ConfigPage


class NoncommercialFinancial(wx.App):
    def OnInit(self):
        self.frame_0 = ConfigPage(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame_0)
        self.frame_0.Show()
        return True

# end of class NoncommercialFinancial

if __name__ == "__main__":
    app = NoncommercialFinancial(0)
    app.MainLoop()
