# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Sun Jul 16 21:30:58 2023
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class BudgetWorksheet(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: BudgetWorksheet.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((640, 625))
        self.SetTitle("frame_1")
        self.SetBackgroundColour(wx.Colour(129, 143, 74))

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        organization_name = wx.StaticText(self.panel_1, wx.ID_ANY, u"The Spiritual Assembly of the Bahá'ís of Harnett County", style=wx.ALIGN_CENTER_HORIZONTAL)
        organization_name.SetForegroundColour(wx.Colour(50, 50, 204))
        organization_name.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_1.Add(organization_name, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 4)

        budget_worksheet = wx.StaticText(self.panel_1, wx.ID_ANY, "Budget Worksheet", style=wx.ALIGN_CENTER_HORIZONTAL)
        budget_worksheet.SetForegroundColour(wx.Colour(50, 50, 204))
        budget_worksheet.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_1.Add(budget_worksheet, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.BOTTOM, 4)

        static_line_1 = wx.StaticLine(self.panel_1, wx.ID_ANY)
        static_line_1.SetBackgroundColour(wx.Colour(176, 192, 177))
        sizer_1.Add(static_line_1, 0, wx.EXPAND, 0)

        grid_sizer_1 = wx.FlexGridSizer(14, 4, 2, 2)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        annual_budget = wx.StaticText(self.panel_1, wx.ID_ANY, "Annual\nBudget", style=wx.ALIGN_CENTER_HORIZONTAL)
        annual_budget.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(annual_budget, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        ytd_actual = wx.StaticText(self.panel_1, wx.ID_ANY, "Year-to-Date\nActual", style=wx.ALIGN_CENTER_HORIZONTAL)
        ytd_actual.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(ytd_actual, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        monthly_budget = wx.StaticText(self.panel_1, wx.ID_ANY, "Monthly\nBudget", style=wx.ALIGN_CENTER_HORIZONTAL)
        monthly_budget.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(monthly_budget, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        begging_cash_balance = wx.StaticText(self.panel_1, wx.ID_ANY, "BEGGING CASH BALANCE AS  OF:")
        begging_cash_balance.SetForegroundColour(wx.Colour(50, 50, 204))
        begging_cash_balance.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_1.Add(begging_cash_balance, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        fisical_start_date = wx.StaticText(self.panel_1, wx.ID_ANY, "", style=wx.ALIGN_CENTER_HORIZONTAL)
        fisical_start_date.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(fisical_start_date, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cash in Bank", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_1.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        self.text_ctrl_1 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_1.SetBackgroundColour(wx.Colour(176, 192, 177))
        self.text_ctrl_1.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(self.text_ctrl_1, 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "OCS Holdings", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_2.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        self.text_ctrl_2 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_2.SetBackgroundColour(wx.Colour(176, 192, 177))
        self.text_ctrl_2.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(self.text_ctrl_2, 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Total Cash", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_3.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        self.text_ctrl_3 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_3.SetBackgroundColour(wx.Colour(176, 192, 177))
        self.text_ctrl_3.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(self.text_ctrl_3, 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        income = wx.StaticText(self.panel_1, wx.ID_ANY, "INCOME")
        income.SetForegroundColour(wx.Colour(50, 50, 204))
        income.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_1.Add(income, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Monitary Contributions", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_4.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        self.text_ctrl_4 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_4.SetBackgroundColour(wx.Colour(176, 192, 177))
        self.text_ctrl_4.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(self.text_ctrl_4, 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "MISC", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_5.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Other", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_6.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(label_6, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        self.text_ctrl_5 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_5.SetBackgroundColour(wx.Colour(176, 192, 177))
        self.text_ctrl_5.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(self.text_ctrl_5, 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class BudgetWorksheet
