# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Sun Jul 16 21:30:58 2023
#

import wx
# begin wxGlade: dependencies
import wx.adv
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ConfigPage(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ConfigPage.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((436, 260))
        self.SetTitle("frame")
        self.SetBackgroundColour(wx.Colour(129, 143, 74))

        # Menu Bar
        self.global_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, "Load", "")
        wxglade_tmp_menu.Append(wx.ID_ANY, "Save", "")
        wxglade_tmp_menu.Append(wx.ID_ANY, "Save As", "")
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_ANY, "Close", "")
        wxglade_tmp_menu.Append(wx.ID_ANY, "Exit", "")
        self.global_menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        self.global_menubar.Append(wxglade_tmp_menu, "Edit")
        wxglade_tmp_menu = wx.Menu()
        self.global_menubar.Append(wxglade_tmp_menu, "Windows")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, "Manual", "")
        wxglade_tmp_menu.Append(wx.ID_ANY, "Releases", "")
        wxglade_tmp_menu.Append(wx.ID_ANY, "About", "")
        self.global_menubar.Append(wxglade_tmp_menu, "Help")
        self.SetMenuBar(self.global_menubar)
        # Menu Bar end

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        page_title = wx.StaticText(self, wx.ID_ANY, "Organization Configuration", style=wx.ALIGN_CENTER_HORIZONTAL)
        page_title.SetMinSize((280, 30))
        page_title.SetForegroundColour(wx.Colour(50, 50, 204))
        page_title.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_1.Add(page_title, 0, wx.ALL | wx.EXPAND, 0)

        grid_sizer_1 = wx.FlexGridSizer(4, 2, 0, 2)
        sizer_1.Add(grid_sizer_1, 0, wx.EXPAND, 0)

        org_name = wx.StaticText(self, wx.ID_ANY, "Organization Name:")
        org_name.SetMinSize((172, 23))
        org_name.SetForegroundColour(wx.Colour(50, 50, 204))
        org_name.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        org_name.SetFocus()
        grid_sizer_1.Add(org_name, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.TOP, 6)

        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.text_ctrl_1.SetMinSize((250, 32))
        self.text_ctrl_1.SetBackgroundColour(wx.Colour(176, 192, 177))
        self.text_ctrl_1.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(self.text_ctrl_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT | wx.TOP, 6)

        total_membership = wx.StaticText(self, wx.ID_ANY, "Total Membership:")
        total_membership.SetForegroundColour(wx.Colour(50, 50, 204))
        total_membership.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_1.Add(total_membership, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.TOP, 6)

        self.text_ctrl_2 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.text_ctrl_2.SetMinSize((50, 32))
        self.text_ctrl_2.SetBackgroundColour(wx.Colour(176, 192, 177))
        self.text_ctrl_2.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(self.text_ctrl_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT | wx.TOP, 6)

        treasurer = wx.StaticText(self, wx.ID_ANY, "Treasurer:")
        treasurer.SetForegroundColour(wx.Colour(50, 50, 204))
        treasurer.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_1.Add(treasurer, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.TOP, 6)

        self.text_ctrl_3 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.text_ctrl_3.SetMinSize((250, 32))
        self.text_ctrl_3.SetBackgroundColour(wx.Colour(176, 192, 177))
        self.text_ctrl_3.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(self.text_ctrl_3, 0, wx.RIGHT | wx.TOP, 6)

        fiscal_year = wx.StaticText(self, wx.ID_ANY, "Start of Fiscal Year:")
        fiscal_year.SetForegroundColour(wx.Colour(50, 50, 204))
        fiscal_year.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_1.Add(fiscal_year, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.TOP, 6)

        self.datepicker_ctrl_1 = wx.adv.DatePickerCtrl(self, wx.ID_ANY)
        self.datepicker_ctrl_1.SetMinSize((115, 32))
        self.datepicker_ctrl_1.SetBackgroundColour(wx.Colour(176, 192, 177))
        self.datepicker_ctrl_1.SetForegroundColour(wx.Colour(50, 50, 204))
        grid_sizer_1.Add(self.datepicker_ctrl_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT | wx.TOP, 6)

        self.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class ConfigPage
